# Generated by Django 5.2.7 on 2025-10-25 02:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloodBag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('blood_group', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')])),
                ('rhesus', models.CharField(choices=[('POS', '+'), ('NEG', '-')])),
            ],
        ),
        migrations.CreateModel(
            name='BloodBank',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=127)),
                ('email', models.EmailField(max_length=127, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], default='M')),
                ('date_birth', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(max_length=127, unique=True)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('blood_group', models.CharField(max_length=1)),
                ('rhesus', models.CharField(max_length=1)),
                ('last_give', models.DateField(blank=True, null=True)),
                ('password', models.CharField(max_length=255)),
                ('historique_medical', models.FileField(blank=True, null=True, upload_to='medical_histories/')),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('SENT', 'Envoyée'), ('RECEIVED', 'Reçue'), ('IN_PROGRESS', 'En cours de traitement'), ('RESOLVED', 'Résolue'), ('CANCELLED', 'Annulée'), ('FAILED', 'Échouée')], default='PENDING', max_length=20)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('Resolved_date', models.DateField(blank=True, null=True)),
                ('blood_groupe', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')])),
                ('rhesus', models.CharField(choices=[('POS', '+'), ('NEG', '-')])),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emitted_alerts', to='apiBloodLink.bloodbank')),
            ],
        ),
        migrations.CreateModel(
            name='BloodTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='apiBloodLink.bloodbank')),
                ('blood_bag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='apiBloodLink.bloodbag')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='apiBloodLink.provider')),
            ],
        ),
        migrations.AddField(
            model_name='bloodbank',
            name='blood_bags',
            field=models.ManyToManyField(related_name='banks', through='apiBloodLink.BloodTransaction', to='apiBloodLink.bloodbag'),
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('grade', models.CharField(choices=[('INT', 'Interne'), ('RES', 'Résident'), ('ASS', 'Assistant médical'), ('SPC', 'Spécialiste'), ('CHS', 'Chef de service'), ('PRF', 'Professeur')], default='INT', max_length=4)),
                ('speciality', models.CharField(choices=[('GP', 'Généraliste'), ('CD', 'Cardiologue'), ('NE', 'Neurologue'), ('OR', 'Orthopédiste'), ('PD', 'Pédiatre')], default='GP', max_length=2)),
                ('password', models.CharField(max_length=255)),
                ('blood_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked', to='apiBloodLink.bloodbank')),
            ],
        ),
        migrations.CreateModel(
            name='BloodRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date_request', models.DateTimeField(auto_now_add=True)),
                ('blood_group', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')])),
                ('rhesus', models.CharField(choices=[('POS', '+'), ('NEG', '-')])),
                ('quantity', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvée'), ('rejected', 'Rejetée')], default='pending', max_length=8)),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blood_requests', to='apiBloodLink.bloodbank')),
                ('docteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood_requests', to='apiBloodLink.doctor')),
            ],
        ),
        migrations.AddField(
            model_name='bloodbag',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='belong_to', to='apiBloodLink.provider'),
        ),
        migrations.CreateModel(
            name='AlerteReceive',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'En attente de réponse'), ('RESPONDED', 'Répondue'), ('COMPLETED', 'Terminée avec succès'), ('CANCELLED', 'Annulée')])),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='apiBloodLink.alert')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='apiBloodLink.provider')),
            ],
            options={
                'unique_together': {('alert', 'provider')},
            },
        ),
    ]
