# Generated by Django 5.2.7 on 2025-10-23 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiBloodLink', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodrequest',
            name='blood_group',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')]),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='rhesus',
            field=models.CharField(choices=[('POS', '+'), ('NEG', '-')]),
        ),
    ]
