# Generated by Django 5.2.7 on 2025-10-23 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiBloodLink', '0002_alter_bloodrequest_blood_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodtransaction',
            name='transaction_type',
        ),
    ]
