# Generated by Django 5.2.7 on 2025-10-24 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiBloodLink', '0003_remove_bloodtransaction_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodbag',
            name='provider',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='belong_to', to='apiBloodLink.provider'),
            preserve_default=False,
        ),
    ]
